# Generated by Django 3.2.3 on 2021-05-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
